### ISSUE TITLE
How to detach again from screen?

### ISSUE THREAD

**Issue by TylerNakamura** [felixmc/Bash-Scripts#1]
In this article: https://felixmilea.com/2014/12/running-bash-commands-background-properly/

You mentioned how to start a process in a given screen, ie:

``` bash
screen -d -m -S "minecraft session" minecraft
```

Lets say you reattach with something like:

``` bash
screen -r <number>
```

How would you then again detach, while leaving the process running?

**Comment by felixmc** [comment]
press `Ctrl-a` `Ctrl-d` in the terminal

**Comment by TylerNakamura** [comment]
Awesome, thanks
